### ISSUE TITLE
CUDA 11 support

### ISSUE THREAD

**Issue by chentairan** [AdaCompNUS/hyp-despot#2]
Hi, Thank you for all the work you do!
I am trying to use hyp-despot, but I found some problems with it compiling on CUDA version 11.3, attached is the error log when compiling. Do you have some suggestions for modifying GPUutils?
[build.make.000.log](https://github.com/AdaCompNUS/hyp-despot/files/7755914/build.make.000.log)

Best,
Tairan Chen

**Comment by cindycia** [comment]
I updated the repo. Can you try again?

**Comment by chentairan** [comment]
Hi,
Thank you very much for your prompt reply. I reattempted to compile, but it still seems to report errors. Attached is the make log file.
[make_log.txt](https://github.com/AdaCompNUS/hyp-despot/files/7782631/make_log.txt)

Best,
Tairan Chen

**Comment by cindycia** [comment]
It compiles fine on my side with CUDA 11. Can you send me the full log? You can also try run make clean before re-compilation.

**Comment by chentairan** [comment]
Here is the full log
[make_log.txt](https://github.com/AdaCompNUS/hyp-despot/files/7783627/make_log.txt)

**Comment by cindycia** [comment]
Sorry for the late update. I correct the line raising the error.

**Comment by chentairan** [comment]
Thank you very much for your help, I modified the example code a little, solved all the compilation problems, and have submitted the pull request

Best,
Tairan Chen
