### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by DP1997** [AdaCompNUS/hyp-despot#4]
Hi,
I think that I am encountering a memory leak when running HyP-DESPOT with the shipped examples.

The behaviour is very easy to replicate:
1. clone Hyp-DESPOT github repo

2. change RunPlanning to RunEvaluation in the main.cu of both examples in order to allow multiple runs
<img width="730" alt="hyp_despot_issue_1" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/b0e78ef9-b144-4937-ab4a-ba5f1629194d">

3. change the number of runs to 100 in RunEvaluation in order to replicate the behaviour of HyP-DESPOT when executed over long periods of time as is commonly the case in real-world applications
<img width="917" alt="hyp_despot_issue_2" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/7bf530bf-972f-42f2-8091-6124b0d206db">

4. build both examples (unknown_nav and rock_sample_mars)

5.  execute either one of them with minimal/no arguments, i.e. ./hyp_despot_unknav or ./hyp_despot_mars

6. start htop in a separate terminal to view process resource consumption live

7. in a matter of minutes the physical memory consumed by either example grows from MB to GB and is killed by the OS eventually (1h for my local system, 3h for a compute cluster) due to having acquired all of the available memory, i.e. it is not stopping.

Here are some example snapshots during execution at different points in time (right after having been started and after having ran for some time). Please not that the TIME+ has to be divided by the number of processes spawned (which are listed separately, but whose resource are accumulated in 1 process) by the programm (default 5) which only exacerbates the issue.

Unknown_nav:
after ~1min:
<img width="757" alt="hyp_despot_issue_3" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/626adea1-c051-40dc-b4f5-c58681253424">

after ~12min:
<img width="763" alt="hyp_despot_issue_5" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/11f9ee88-60c0-4a59-9c6e-7dc4e9ddb1d2">

rock_sample_mars:
after ~10s:
<img width="539" alt="hyp_despot_issue_6" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/1638df7c-cf5e-463c-94ab-41d5c4407a5b">

after ~8min:
<img width="678" alt="hyp_despot_issue_7" src="https://github.com/AdaCompNUS/hyp-despot/assets/39188501/11178645-2bb8-4b52-a105-1d37b71b38ce">

I would expect that the memory consumption of HyP-DESPOT stays consistent or minimally changing, but never continuously growing over its lifetime.
My current workaround is to periodically re-start HyP-DESPOT.

**Comment by BoluoMonster** [comment]
It appears that a variable named "allocated_" of "MemoryObject" is not properly initialized, resulting in expanded nodes not being freed in time after the planning is complete. You can fetch the latest repo to check the modification.

**Comment by DP1997** [comment]
> It appears that a variable named "allocated_" of "MemoryObject" is not properly initialized, resulting in expanded nodes not being freed in time after the planning is complete. You can fetch the latest repo to check the modification.

thanks that seems to have fixed the issue :)
